baseURL = "https://Hzy-0313.github.io/"
title = "sun"
theme = "blowfish"
relativeURLs = true
[language]
  [language.zh]
    locale = "zh-CN"
    languageName = "中文"
    weight = 1

[taxonomies]
tag = "tags"
category = "categories"

[[menu.main]]
name = "首页"
url = "/"
weight = 1
[[menu.main]]
name = "文章"
url = "/posts/"
weight = 2

[params]
author = "H"
subtitle = "学习记录博客"