name: Deploy Hugo Blog
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - name: 拉取代码与子模块
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: 配置 Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest
          extended: true
      - name: 清理缓存，构建站点（根目录直接打包，不切exampleSite）
        run: |
          hugo mod clean --all
          hugo --gc --minify --baseURL "https://hzy-0313.github.io/"
      - name: 部署到 gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public