name: Deploy Hugo Blog
on:
  push:
    branches: [ main ]
jobs:
  build-deploy:
    runs-on: ubuntu-24.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      # 拉取源码+主题子模块（关键，不然主题丢失）
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      # 安装兼容Blowfish的Hugo版本（最低0.158.0）
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.158.0"
          extended: true

      # 打包生产环境静态网页
      - name: Build static site
        run: hugo --minify -e production

      # 自动发布到gh-pages分支
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public